[package]
name = "utilities"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { 
    git = "https://github.com/bevyengine/bevy.git", 
    rev = "8a555d1", 
    default-features = false, 
    features = [
        "3d"
    ] 
}